export const config = {
  contractAddresses: {
    1: "0x3af3cc4930ef88F4afe0b695Ac95C230E1A108Ec",
    137: "0x3af3cc4930ef88F4afe0b695Ac95C230E1A108Ec",
    56: "0x3af3cc4930ef88F4afe0b695Ac95C230E1A108Ec",
    42161: "0x3af3cc4930ef88F4afe0b695Ac95C230E1A108Ec",
  },
  methods: {
    batchSwap: "swapTokensToTokens",
  },
  abi: [
    "constructor(uint256[3] fees_, address[] routers_, tuple(bool isSupported, uint256 fees)[] routerDetails_, address governor_, address aggregationRouter_, address wNative_, address protocolFeeVault_, address feeDiscountNft_)",
    "event GovernanceChanged(address indexed formerGov, address indexed newGov)",
    "event LiquidityAdded(address indexed sender, address indexed recipient, tuple(address token, uint256 amount)[] inputTokens, address outputLp, uint256[3] returnAmounts, uint256[2] feeBps)",
    "event LpSwapped(address indexed sender, address indexed recipient, tuple(tuple(address token, uint256 amount)[] lpInput, tuple(address token, uint256 amount)[] lpOutput) swapInfo, uint256[2] feeBps)",
    "event ProjectAdded(uint256 indexed id)",
    "event ProjectFeeUpdated(uint256 indexed id)",
    "event ProjectFeeVaultUpdated(uint256 indexed id)",
    "event ProjectStatusDisabled(uint256 indexed id)",
    "event ProtocolFeeUpdated()",
    "event ProtocolFeeVaultUpdated()",
    "event RoutersUpdated(address[] routers, tuple(bool isSupported, uint256 fees)[] details)",
    "event TokensRescued(address indexed to, address indexed token, uint256 amount)",
    "event TokensSwapped(address indexed sender, address indexed recipient, tuple(address srcToken, address dstToken, uint256 amount, uint256 returnAmount)[] swapInfo, uint256[2] feeBps)",
    "event TokensTransferred(address indexed sender, tuple(address recipient, tuple(address token, uint256 amount)[] data)[] details, uint256[2] feeBps)",
    "function AGGREGATION_ROUTER() view returns (address)",
    "function BPS_DENOMINATOR() view returns (uint256)",
    "function MAX_FEE() view returns (uint256)",
    "function addProject(uint256[3] fees_, address feeVault_)",
    "function batchTransfer(tuple(address recipient, tuple(address token, uint256 amount, bytes permit)[] data)[] data_, uint256 projectId_, uint256 nftId_) payable",
    "function calculateOptimalSwapAmount(uint256 amountA_, uint256 amountB_, uint256 reserveA_, uint256 reserveB_, address router_) view returns (uint256)",
    "function changeGovernance(address newGov_)",
    "function disableProject(uint256 projectId_)",
    "function feeDiscountNft() view returns (address)",
    "function governance() view returns (address)",
    "function nextProjectId() view returns (uint256)",
    "function projectFeeBps(uint256, uint8) view returns (uint256)",
    "function projectFeeVault(uint256) view returns (address)",
    "function protocolFeeBps(uint8) view returns (uint256)",
    "function protocolFeeVault() view returns (address)",
    "function rescueFunds(address token_, address to_, uint256 amount_)",
    "function routers(address) view returns (bool isSupported, uint256 fees)",
    "function swapLpToTokens(tuple(address router, address token, uint256 amount, bytes permit, address[] tokenAToPath, address[] tokenBToPath)[] lpSwapDetails_, tuple(address router, uint256 sizeBps, uint256 minReturnAmount, address[] nativeToOutputPath)[] wEthSwapDetails_, address recipient_, uint256 projectId_, uint256 nftId_)",
    "function swapTokensToLp(tuple(address executor, tuple(address srcToken, address dstToken, address srcReceiver, address dstReceiver, uint256 amount, uint256 minReturnAmount, uint256 flags, bytes permit) desc, bytes routeData, bytes permit)[] data_, tuple(address router, address token, uint256 amount, bytes permit, address[] tokenAToPath, address[] tokenBToPath)[] lpSwapDetails_, tuple(address router, address lpToken, uint256 minReturnAmount, address[] nativeToToken0, address[] nativeToToken1) outputLpDetails_, address recipient_, uint256 projectId_, uint256 nftId_) payable",
    "function swapTokensToTokens(tuple(address executor, tuple(address srcToken, address dstToken, address srcReceiver, address dstReceiver, uint256 amount, uint256 minReturnAmount, uint256 flags, bytes permit) desc, bytes routeData, bytes permit)[] data_, address recipient_, uint256 projectId_, uint256 nftId_) payable",
    "function unoSwapTokensToTokens(tuple(address router, uint256 amount, uint256 minReturnAmount, address[] path, bytes permit)[] swapData_, address recipient_, uint256 projectId_, uint256 nftId_) payable",
    "function updateProjectFee(uint256 projectId_, uint8[] feeTypes_, uint256[] fees_)",
    "function updateProjectFeeVault(uint256 projectId_, address feeVault_)",
    "function updateProtocolFee(uint8[] feeTypes_, uint256[] fees_)",
    "function updateProtocolFeeVault(address newProtocolFeeVault_)",
    "function updateRouters(address[] routers_, tuple(bool isSupported, uint256 fees)[] routerDetails_)",
    "function wNative() view returns (address)",
  ],
};
